--SQL Requests--

CREATE DATABASE demo_db;


CREATE TABLE IF NOT EXISTS products
( id INTEGER NOT NULL AUTO_INCREMENT,
  name VARCHAR(128) NOT NULL,
  quota INTEGER NOT NULL,
  price DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (id)
);


